version: '3'
services:
  postgres:
    image: postgres:13
    container_name: short-url-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: short_url